on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_GRADLE_GH_ORG_BOARD_ACCESS_TOKEN }}
jobs:
  add_to_gh_projects:
    runs-on: ubuntu-latest
    name: Adds issues to GH projects
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add labeled issues
        uses: ./add-labeled-issues
        id: add-issues
